name: flutter_notification_center
description: A wrapper for the observer pattern for Flutter in the style of the iOS Notification Center.
version: 0.1.0
homepage: https://github.com/flyrboy96
author: Bruce Brookshire <bruce.t.brookshire@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
